config/routes.rb
Teste1::Application.routes.draw do
  

resources :desenhozinhos
  

 

 
  

  root :to => 'desenhozinhos#index'
 

end

app/models/desenhozinho.rb
class Desenhozinho < ActiveRecord::Base
	has_many:pontinhos
end

app/models/pontinho.rb
class Pontinho < ActiveRecord::Base
	belongs_to:desenhinho
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/desenhozinhos_controller.rb
class DesenhozinhosController < ApplicationController
  # GET /desenhozinhos
  # GET /desenhozinhos.json
  def index
    @desenhozinhos = Desenhozinho.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @desenhozinhos }
    end
  end

  def show
    
    @desenhozinho=Desenhozinho.create(:NumDesenho=>($anumd))
    i=0
    loop do
      
        Pontinho.create(:NumDesenho=>@desenhozinho.id ,:NumPonto=>i , :CX=>$ada[i] , :CY=>$ada[i+1])
        i=i+2
        break if i>=$ada.length     
    end
    respond_to do |format|
      format.html {render action: "index"}# index.html.erb
      format.json { render json: @desenhozinhos }
    end     
  end

  def mostradesenho
     @desenhozinho = Desenhozinho.find(params[:id])
     @desenhozinho.Pontinho(:NumDesenho)

  end  
  # POST /desenhozinhos
  # POST /desenhozinhos.json
  def create
    @desenhozinho = Desenhozinho.new(params[:desenhozinho])

    respond_to do |format|
      if @desenhozinho.save
        format.html { redirect_to @desenhozinho, notice: 'Desenhozinho was successfully created.' }
        format.json { render json: @desenhozinho, status: :created, location: @desenhozinho }
      else
        format.html { render action: "new" }
        format.json { render json: @desenhozinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /desenhozinhos/1
  # PUT /desenhozinhos/1.json
  def update
    @desenhozinho = Desenhozinho.find(params[:id])

    respond_to do |format|
      if @desenhozinho.update_attributes(params[:desenhozinho])
        format.html { redirect_to @desenhozinho, notice: 'Desenhozinho was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @desenhozinho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desenhozinhos/1
  # DELETE /desenhozinhos/1.json

  def destroy
    @desenhozinhos=Desenhozinho.all
    @pontinhos=Pontinho.all
    if Desenhozinho.exists?
        @desenhozinhos.each do |d|
            d.destroy
            d.save
        end
        
        @pontinhos.each do |p|
            p.destroy
            p.save
        end 


    end 
    respond_to do |format|
      format.html {render action: "index"}# index.html.erb
      format.json { render json: @desenhozinhos }
    end  
  end
end

app/controllers/pontinhos_controller.rb
class PontinhosController < ApplicationController
  
  $ada
  def index
    @pontinhos = Pontinho.all
  end
  def new
    @pontinho=Pontinho.new
  end
  def create
   
    @pontinho=Pontinho.new(params[:desenho])
    respond_to do |format|
      format.html { redirect_to(index) }
      format.xml  { head :ok }
    end
  end

  

  def show
    @pontinhos = Pontinho.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pontinho }
    end
  end


  def destroy
      @pontinhos=Pontinho.all
      if Pontinho.exists?
        @pontinhos.each do |p|
            p.destroy
        end
      end   
    
      

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desenhozinhos_helper.rb
module DesenhozinhosHelper
end

app/helpers/pontinhos_helper.rb
module PontinhosHelper
end

app/views/desenhozinhos/index.html.erb
<%= form_tag do %>
 
<%$ada=[]%>


<script type="text/javascript" id="JSID" data-message>
//CABEÇALHOS DAS FUNCOES

//Vars Globais de JS
DesenhoActual = new Array(); //estrutura para guardar o desenho atual recoorre-se ao constutor coordenada

var strHTML="";

 //numero de cliques no canvas que é igual ao num de pts do desenho
NumClick=0;
var LastX; //para guardar o ultimo ponto de modo a fazer o desenho
var LastY;

document.addEventListener("DOMContentLoaded", init, false); //o orelhas dos eventos
var ctx; //contexto do canvas
var BLA;
// DEFINIÇÃO DE FUNÇÕES

function init() //está sempre À espera do clique no canvas com o listener
      {
        var canvas = document.getElementById("myCanvas");
        canvas.addEventListener("mousedown", getPosition, false);
        ctx=canvas.getContext("2d");
      }
// Constroi a coordenada 
function coordenada( pini, pfim ) {
   this.pini = pini;
   this.pfim = pfim;
}

function getPosition(event) //DISPARA COM UM CLIQUE NO CANVAS
{
   
    var totalOffsetX = 0;
    var totalOffsetY = 0;
    var canvasX = 0;
    var canvasY = 0;
    var currentElement = this;
    //detetar a coordenada no canvas
    do{
        totalOffsetX += currentElement.offsetLeft;
        totalOffsetY += currentElement.offsetTop;
      }
    while(currentElement = currentElement.offsetParent)

    canvasX = event.pageX - totalOffsetX;
    canvasY = event.pageY - totalOffsetY;
  
    if (NumClick>0)
    { 
      //A ESCREVER no canvas");
      ctx.beginPath(); 
      ctx.lineWidth="3";
      ctx.strokeStyle="blue"; 
      ctx.moveTo(LastX,LastY);
      ctx.lineTo(canvasX,canvasY);
      ctx.stroke(); // Draw it
      
    }
    else
    {
   
    }
  
   

    //Actualiza 
    LastX=canvasX;
    LastY=canvasY;
   

    DesenhoActual[NumClick] = new coordenada(canvasX,canvasY);
    
    
   
   
    
    NumClick=NumClick+1;

    return true

}

$(function () 
{ 
  $('#GuardaLimpaID').click(function ($ada)
  {
  var CodigoContrutor;  
  if (NumClick<2)
    {
      alert("O seu desenho actual não pode ser guardado pois não tem um segmento de recta criado")
      return false
    }
  else
    {
      //constroi o array com os pontos das coordenadas do desenho actual que se encontra no canvas
      strHTML="[";
      for (i=0; i<NumClick-1 ; i++)
          {     
          //numpontonodpesenho,x,y  
          strHTML+= DesenhoActual[i].pini+","+DesenhoActual[i].pfim+","; 

          // DesenhoActual[i].pini.string + "," + DesenhoActual[i].pfim.string);    
          }  
         
      strHTML+= DesenhoActual[NumClick-1].pini+","+DesenhoActual[NumClick-1].pfim+"]";

      //LIMPA DESENHO
      
      this.value=strHTML;
      //document.getElementById("ArrayId").innerHTML=strHTML;
     
      $ada=strHTML;
       document.getElementById("ArrayId").value=strHTML;
      //document.getElementById("JSID").getAttribute("data-message")=strHTML;
      ctx.fillStyle="white";  
      ctx.fillRect(0,0,400,200);
      NumClick=0;
      alert(document.getElementById("ArrayId").value);
     
      return true
    }
  })
});

function DesenhaCanvas(adesenho) //recebe um array de coordenadas ordenado e escreve no canvas as linhas correspondentes a esses pontos
 { 
  if (adesenho.length==0)
  {
  }
  else
  {  
      ctx.fillStyle="white";  
      ctx.fillRect(0,0,400,200);
      NumClick=0;
      for (var i = 0; i <adesenho.length; i=i+2) {
  
          //actualiza a var global com o desenho actual para continuar a desenhar-se
          DesenhoActual[i]=new coordenada(adesenho[i],adesenho[i+1]);
          DesenhoActual[i]=new coordenada(adesenho[i+2],adesenho[i+3]);
          
          //desenha no canvas a partir dos pontos que vieram em adesenho
          ctx.beginPath(); 
          ctx.lineWidth="3";
          ctx.strokeStyle="blue"; 
          ctx.moveTo(adesenho[i],adesenho[i+1]);
          ctx.lineTo(adesenho[i+2],adesenho[i+3]);
          ctx.stroke(); // Draw it
      
          LastX=   adesenho[i+2];
        LastX=   adesenho[i+3];
                     
      };
     NumClick=adesenho.length/2;
    }
}  


$(function () 
{
  $('#ApagaTudoID').click(function () 
  {
  
  var r=confirm("Atenção deseja mesmo apagar todos os desenhos da Base de Dados?");
  if (r==true)
      {   
      NumClick=0;

      //LIMPA DESENHO
      ctx.fillStyle="white";
      ctx.fillRect(0,0,400,200);
    //  this.value="APAGOU OS DESENHOS TODOS DA BD!!!!"
      //alert(this.value);  
     }

  else
     {  

     }
       
  return r    
 })

});
</script>


<h1>Problema 1 - Rails e HTML5 Canvas</h1>


<%anump=0%>

<%$anumd=0%>
<%@desenhozinhos=Desenhozinho.all%>

<table border="0" >
  <tr>
    <div type="hidden" id="ArrayId2" value=""></div>
ada que é uma var global do ruby ($ada) devia ter o q vai no alert.. mas estou a meter sempre isto qd faço save and clear<%=$ada%>
    
    <th> Lista de desenhos</th>
    
    <td id="desNum"> Desenho->
        <%if Desenhozinho.count==0%>
            <%= $anumd=1%>
          <%else%>
            <%= $anumd=Desenhozinho.maximum("NumDesenho")+1 %>
        <%end%>
    </td> 
  </tr>
  <tr>  
       <td id="ListaDesenhos">
            <% @desenhozinhos.each do |d| %>    
                      Desenho <%= link_to d.NumDesenho , :id=>d.NumDesenho %><p> 
            <% end %>
      </td>

</td>

    <td>
        <canvas id="myCanvas" data-msgNP=0 data-msgYY=0 data-msgXX=0 width="400" height="200"  style="border:1px solid #000000;" > 

        </canvas>
    </td>
  </tr>
  <tr>
    <td> </td>
    
    <td>
      <button href=# id="GuardaLimpaID" type="button" onclick="SaveAndClear();"> 
       <input id="ArrayId" type="hidden" value=""></input>   
        <%= link_to 'Save and Clear',  '/desenhozinhos/saveandclear' , :id=>"saveandclear" %>
      </button> 

      <button href=# id="ApagaTudoID" type="button" value="Delete All" onclick="DeleteAll()" > 
           
            <%= link_to 'Delete All', '/desenhozinhos/destroy' , :method=>:delete  %>
                      
                    
             
         </button>      

        <button  type="button" value="valor" onclick="DesenhaCanvas([0,0,200,200]);">constroi um desenho a partir de um array </button>


   </td>   
      </td>
      
             
      <tr>
        <td id="RowCount"> Num de regs de pontinhos <%= Pontinho.count %> </td>
      </tr>
<tr>
        <td id="RowCountDesenhos"> Num de regs de desenhos <%= Desenhozinho.count %> </td>
      </tr>

 
</table>


<tr>
<% end %>

app/views/desenhozinhos/show.html.erb
p id="notice"><%= notice %></p>

<p>
  <b>Nome do desenho:</b>
  <%= @desenhozinho.NomeDesenho %>
</p>


<%= link_to 'Edit', edit_desenhozinho_path(@desenhozinho) %> |
<%= link_to 'Back', desenhozinhos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Teste1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "points_data" %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<% unless flash[:aviso].blank? %>
		<div id="aviso"><%= flash[:aviso] %></div>
	<% end %>

<%= yield %>
</div>
</body>

</html>

app/views/pontinhos/destroy.html.erb
<h1> Base de Dados Limpa</h1>
current_page?(:action => 'process')
<%= link_to 'Back', "/pontinhos" %> 

app/views/pontinhos/index.html.erb
<script type="text/javascript" id="JSID" data-message>
//CABEÇALHOS DAS FUNCOES

//Vars Globais de JS
DesenhoActual = new Array(); //estrutura para guardar o desenho atual recoorre-se ao constutor coordenada

var strHTML="";

 //numero de cliques no canvas que é igual ao num de pts do desenho
NumClick=0;
var LastX; //para guardar o ultimo ponto de modo a fazer o desenho
var LastY;

document.addEventListener("DOMContentLoaded", init, false); //o orelhas dos eventos
var ctx; //contexto do canvas
var BLA;
// DEFINIÇÃO DE FUNÇÕES

function init() //está sempre À espera do clique no canvas com o listener
      {
        var canvas = document.getElementById("myCanvas");
        canvas.addEventListener("mousedown", getPosition, false);
        ctx=canvas.getContext("2d");
      }
// Constroi a coordenada 
function coordenada( pini, pfim ) {
   this.pini = pini;
   this.pfim = pfim;
}

function getPosition(event) //DISPARA COM UM CLIQUE NO CANVAS
{
   
    var totalOffsetX = 0;
    var totalOffsetY = 0;
    var canvasX = 0;
    var canvasY = 0;
    var currentElement = this;
    //detetar a coordenada no canvas
    do{
        totalOffsetX += currentElement.offsetLeft;
        totalOffsetY += currentElement.offsetTop;
      }
    while(currentElement = currentElement.offsetParent)

    canvasX = event.pageX - totalOffsetX;
    canvasY = event.pageY - totalOffsetY;
  
    if (NumClick>0)
    { 
      //A ESCREVER no canvas");
      ctx.beginPath(); 
      ctx.lineWidth="3";
      ctx.strokeStyle="blue"; 
      ctx.moveTo(LastX,LastY);
      ctx.lineTo(canvasX,canvasY);
      ctx.stroke(); // Draw it
      
    }
    else
    {
   
    }
  
   
    canvasX
    //Actualiza 
    LastX=canvasX;
    LastY=canvasY;
    
    DesenhoActual[NumClick] = new coordenada(canvasX,canvasY);
    
    
   
   
    
    NumClick=NumClick+1;

    return true

}

$(function () 
{ 
  $('#GuardaLimpaID').click(function ()
  {
  var CodigoContrutor;  
  if (NumClick<2)
    {
      alert("O seu desenho actual não pode ser guardado pois não tem um segmento de recta criado")
      return false
    }
  else
    {
      strHTML="";
      for (i=0; i<NumClick-1 ; i++)
          {     
          //numpontonodpesenho,x,y  
          strHTML+= "[" + i + ","+DesenhoActual[i].pini+","+DesenhoActual[i].pfim+"],"; 

          // DesenhoActual[i].pini.string + "," + DesenhoActual[i].pfim.string);    
          }  
         
      strHTML+= "[" + (NumClick-1) + ","+ DesenhoActual[NumClick-1].pini+","+DesenhoActual[NumClick-1].pfim+"]]";

     
      //LIMPA DESENHO
      
      this.value=strHTML;
      document.getElementById("ArrayId").innerHTML=strHTML;
      document.getElementById("ArrayId").value=strHTML;
      ctx.fillStyle="white";  
      ctx.fillRect(0,0,400,200);
      NumClick=0;
      alert(this.value);
      return true
    }
  })
});


$(function () 
{
  $('#ApagaTudoID').click(function () 
  {
  var codigo_destruidor="";
  var r=confirm("Atenção deseja mesmo apagar todos os desenhos da Base de Dados?");
  if (r==true)
      {   
      NumClick=0;

      //LIMPA DESENHO
      ctx.fillStyle="white";
      ctx.fillRect(0,0,400,200);
      this.value="APAGOU OS DESENHOS TODOS DA BD!!!!"
      alert(this.value);  
     }

  else
     {  

     }
       
  return r    
 })

});
</script>


<h1>Problema 1 - Rails e HTML5 Canvas</h1>

  
<%anump=0%>
<%anumd=0%>


<table border="0" >
  <tr>
    <div type="hidden" id="ArrayId" value="bu" <%$da=%>></div>
    <th> Lista de desenhos</th>
    
    <td id="desNum"> Desenho->
        <%if Pontinho.count==0%>
            <%= anumd=1%>
          <%else%>
            <%= anumd=Pontinho.maximum("NumDesenho") %>
        <%end%>
    </td> 
  </tr>
  <tr>  
       <td id="ListaDesenhos">
            <% Pontinho.order.all(:group => "NumDesenho", :order => "NumDesenho").each do |pontinho| %>
                      desenho <%= link_to "Desenho "+pontinho.NumDesenho, :NumDesenho=>pontinho.NumDesenho %><p> 
            <% end %>
      </td>

</td>

    <td>
        <canvas id="myCanvas" data-msgNP=0 data-msgYY=0 data-msgXX=0 width="400" height="200"  style="border:1px solid #000000;"> 

        </canvas>
    </td>
  </tr>
  <tr>
    <td> </td>
    
    <td>
      <button href=# id="GuardaLimpaID" type="button" onclick="SaveAndClear(); " value> 
         <%= button_to 'SaveAndClear',  :class=>"guardalimpa" %>
      </button>

      <button href=# id="ApagaTudoID" type="button" value="" onclick="DeleteAll()" >

            <%= button_to 'Delete All', :method => :destroy %>
           
   </td>   
      </button> </td>
      
             
      <tr>
        <td id="RowCount"> Num de regs <%= Pontinho.count %> </td>
      </tr>

  <td>
    <%@pontinhos.each do |p|%>

      <tr>
        <td><%= p.NumDesenho %>NumDesenho </td>
        <td><%= p.NumPonto %>NumPonto</td>
        <td><%= p.CX %>CX</td>
        <td><%= p.CY %>CY</td>
      </tr>
    <% end %>
  </td>  
</table>



 
<tr>
Tamanho do ARRAY <%unless $da==nil%>
                      <%=$da.length%>
                  <% end %><p> 
          
CONTEUDO <%=$da%>

</tr>